id: dk.ehmi.eer
canonical: http://medcomehmi.dk/ig/eer
name: EHMI Endpoint Register (EER) IG
title: "DK EHMI Endpoint Register (EER)"
description: The EHMI Endpoint Register (EER) IG
status: draft # draft | active | retired | unknown
version: 2.0.1-draft
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://medcom.dk
  email: ehmi@medcom.dk

dependencies:
  ihe.iti.mcsd: 3.9.0
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 3.0.0
  medcom.fhir.dk.terminology: 1.8.1
  dk.ehmi.terminology: current

menu:
  Home: index.html
  EER and SOR: SOR-EER-mapping.html
  Profiles: profiles.html
  Use-cases: 
    EER Use case 1: eer-Use-case-1.html
    #EER Use case 2: eer-Use-case-2.html
    EER-EAS Use case 4: eas-Use-case-4.html
  Security: 
    Security-en: security-english.html
    Security-da: security-danish.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html
#    mCSD User-stories: EHMI-CSD-User-Stories.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
#  specialUrl: {http://cvr.dk}